// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebgrbeyapjuxeyjoicdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViZ3JiZXlhcGp1eGV5am9pY2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MjkxNDYsImV4cCI6MjA3MzMwNTE0Nn0.DJqcaZxRkqW-Z-IfPSCh19vZ0_dDVCgtsZ5CoEGH99o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});