// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihthnipyfppatlmaajvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlodGhuaXB5ZnBwYXRsbWFhanZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MzEyNDgsImV4cCI6MjA3MzMwNzI0OH0.Of4WTV1kcLbkiHqyixArMq564nEE6x0jXdA4K-X_jdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});